version: '3'
services:
  nginx:
    container_name: php-infrastructure-app-nginx
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - .:/var/app
    depends_on:
      - php
    networks:
      - app_php_network
  php:
    container_name: php-infrastructure-app-app
    build: ./docker/php
    volumes:
      - .:/var/app
    networks:
      - app_php_network
    depends_on:
      - db
    env_file:
      - .env
  db:
    container_name: php-infrastructure-app-db
    image: postgres:14.1-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - app_php_network
networks:
  app_php_network: